### ISSUE TITLE
How to configure MetroLog in Blazor Hybrid

### ISSUE THREAD

**Issue by rich25200** [roubachof/MetroLog#10] opened 2022-11-17 14:28 UTC
### Discussed in https://github.com/roubachof/MetroLog/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **rich25200** November 17, 2022</sup>
Hi,

Could you please tell me how to configure MetroLog in Maui Blazor Hybrid?

I have an error as "BeginScope is not supported on MetroLog"..

Thanks</div>

**Comment by roubachof** [comment] 2023-01-16 09:57
duplicate of #6

**Closed** 2023-01-16 09:57 UTC
